### ISSUE TITLE
Error: Cannot find module 'collections/shim'

### ISSUE THREAD

**Issue by kohlerm** [bahmutov/next-updater#33]
Installation seems to go fine, but when running next-updater I get 
module.js:471
    throw err;
    ^

Error: Cannot find module 'collections/shim'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/next-updater/node_modules/q/q.js:43:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

node --version
v6.11.3

 npm --version
5.4.2

(updated npm, when getting the error, but did not make  a difference)

**Comment by prantlf** [comment]
This appears not to depend on the Node.js version. The file "shim" in the module `collections@2` is missing, when the module is installed by npm. Although it is not used directly from `next-updater`, some other module requires it and the installed version does not fit.

**Workaround:** clone this repository, build the project and use the tool from its source directory:

```sh
git clone https://github.com/bahmutov/next-updater
cd next-updater
npm i
npm i collections
node index.js ...
```
